# Generated by Django 4.2.3 on 2023-09-22 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '', 'verbose_name_plural': 'Таски'},
        ),
    ]
